{% set name = "pyrtcm" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrtcm-{{ version }}.tar.gz
  sha256: 3880a900292aeed6e3d053a68c20c6f183cabe0bd9ad65e74c2a08f4848cc5cc
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pynmeagps >=1.1.5

test:
  imports:
    - pyrtcm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pyrtcm
  description: Python library for parsing RTCM3 protocol messages.
  summary: RTCM3 protocol parser
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyrtcm/
  dev_url: https://github.com/semuconsulting/pyrtcm

extra:
  recipe-maintainers:
    - semuadmin
